Refactor everest-clang-format-image
EVerest/everest-ci pull request #13
Opened 2023-12-13 11:31 UTC by andistorm

* Move everest-clang-format Dockerfile to everest-ci
* Move run-clang-format.py to everest-ci
* Use everest-ci release in everest-clang-format Dockerfile to install clang-format
* Use v15.0.6 instead of v16.0.0
--------
* Add re-release-clang-format workflow that takes a release from llvm-project and re-release it on everest-ci with extracted clang-format
* Add build-and-deploy-docker-image action
* Add build-and-deploy-docker-images workflow that uses this action
* Remove build-kit workflow, use new workflow instead
--------
* Add dependencies to build-kit Dockerfile to allow build on arm64: libffi-dev, rust, cargo, libxml2-dev, libxslt-dev
* Remove `clean up apt` since it is already done automatically for debian based images: https://docs.docker.com/develop/develop-images/instructions/

2023-12-13 15:51 UTC, Dominik-K requested changes
First part of review  (in manner for https://google.github.io/eng-practices/review/reviewer/speed.html).

2023-12-13 15:51 UTC, Dominik-K commented on THIRD_PARTY.md
How about adding this reference, etc. directly to the source file? It needs a copyright header anyway.

2023-12-13 15:51 UTC, Dominik-K commented on .github/workflows/build-and-deploy-docker-images.yaml
> +      - 'v*'
Restrict it to the path where the Docker-images reside. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths.

2023-12-13 15:51 UTC, Dominik-K commented on .github/workflows/build-and-deploy-docker-images.yaml
I suggest that the deploy-step should only be done on tagged versions resp. on default branch (`main`).

Otherwise many unfinished Docker-image tags are lingering around.

2023-12-13 15:51 UTC, Dominik-K commented on github-actions/build-and-deploy-docker-image/action.yaml
> +      working-directory: dockerfile-repo
That decision should be up to the workflow ([using path-inclusions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths); see comment above).

The next step is then obsolete and the `if`s, too.

2023-12-13 15:51 UTC, Dominik-K commented on github-actions/build-and-deploy-docker-image/action.yaml
> +        password: ${{ inputs.github_token }}
Don't we push to GitHub packages instead?

2023-12-13 15:51 UTC, Dominik-K commented on github-actions/build-and-deploy-docker-image/action.yaml
Why is this an extra action? Will it be used somewhere else?

If not, when you move this directly in the workflow, you could remove a lot of `inputs` boilerplate here and in the workflow. That makes it better readable.

2023-12-13 15:51 UTC, Dominik-K commented on docker/images/build-kit/alpine.Dockerfile
> +        libxslt-dev
That's unrelated to this PR, or? :thinking: 
(Same for the other Dockerfile.)

2023-12-13 16:15 UTC, Dominik-K commented on docker/images/build-kit/debian.Dockerfile
> -
Interesting. Can you move this to another, small PR, please? Because https://google.github.io/eng-practices/review/reviewer/speed.html#large

Then I would have directly seen your good PR-description for this :+1: And the "topic" of this PR is more focused.

2023-12-13 16:19 UTC, Dominik-K commented on docker/images/everest-clang-format/Dockerfile
> +RUN apt update && apt upgrade -y
```suggestion
```

Or why is it necessary?

2023-12-13 16:21 UTC, Dominik-K commented on docker/images/build-kit/debian.Dockerfile
> -
BTW: Can you explain how this cache deletion works? I'm curious.

2023-12-13 16:23 UTC, Dominik-K commented on docker/images/everest-clang-format/Dockerfile
> +    wget
How about using `curl` instead? I guess this will be installed instead.

2023-12-13 16:27 UTC, Dominik-K commented on docker/images/everest-clang-format/Dockerfile
> +ENTRYPOINT ["/usr/bin/run-clang-format.py"]
```suggestion
```

Done in next stage.

2023-12-13 16:37 UTC, Dominik-K commented on docker/images/everest-clang-format/Dockerfile
> +ENV CLANG_FORMAT_RELEASE_TAG=llvmorg-15.0.6
1. Why not hardcode the repo in here? Then it's directly obvious that we're getting it from this repo (if I see it correctly.)
2. A `CLANG_FORMAT_VERSION` would make it easier to read and understand ...
3. ... and it should be an `ARG` without any default that the version is set at one place (and could be updated with as few changes as possible, when needed).

2023-12-13 16:39 UTC, Dominik-K commented on docker/images/everest-clang-format/Dockerfile
> +ARG TARGETPLATFORM
```suggestion
```

It's [set automatically with BuildKit](https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope).

2023-12-13 16:42 UTC, Dominik-K commented on .github/workflows/build-and-deploy-docker-images.yaml
> +            image_name: ${{ github.repository_owner }}/everest-clang-format
```suggestion
            image_name: ${{ github.repository_owner }}/run-clang-format
```

As the `ENTRYPOINT` directly uses this kind-of-famous script.

2023-12-14 09:14 UTC, andistorm commented on THIRD_PARTY.md
Could you propose a header? Not sure about how to link such files properly

2023-12-14 09:15 UTC, andistorm commented on .github/workflows/build-and-deploy-docker-images.yaml
> +      - 'v*'
Since each image is in its own directory we would need to restrict here for changes in docker/images,
but restrict again in the composite action `build-and-deploy-docker-image/action.yaml`

2023-12-14 09:17 UTC, andistorm commented on .github/workflows/build-and-deploy-docker-images.yaml
What do you mean with "unfinished Docker-image tags"?

2023-12-14 09:19 UTC, andistorm commented on .github/workflows/build-and-deploy-docker-images.yaml
> +      - 'v*'
Just your comment there.

Since there are individuals paths for the docker images it is not possible to move it compeltly to the workflow trigger

2023-12-14 09:21 UTC, andistorm commented on github-actions/build-and-deploy-docker-image/action.yaml
> +        password: ${{ inputs.github_token }}
Yes we push to githubs docker/container registry
You mean I should rename the input to `container_registry` for example?

2023-12-14 09:23 UTC, andistorm commented on github-actions/build-and-deploy-docker-image/action.yaml
I don't think it makes it more readable, as this composite action encapsulates the task of building and deploying a single image. Currently, the action is not used anywhere else but could be reused. For example in the everest-demo repo

2023-12-14 09:29 UTC, andistorm commented on docker/images/everest-clang-format/Dockerfile
> +RUN apt update && apt upgrade -y
This article: https://pythonspeed.com/articles/security-updates-in-docker/
convinced me to run apt upgrade and install security updates..

2023-12-14 09:30 UTC, andistorm commented on docker/images/everest-clang-format/Dockerfile
> +    wget
Why using curl? Both are not preinstalled

2023-12-14 09:33 UTC, andistorm commented on docker/images/everest-clang-format/Dockerfile
> +ENTRYPOINT ["/usr/bin/run-clang-format.py"]
I added it to have a build stage that hase same behaviour as the resulting stage.
In sense of to jsut trim the result stage down
This way it is possible to use the build stage as build target and run it for debugging purposes

In this case the "trim down" is no that big since the only difference is the `wget` package installed or not

2023-12-14 09:40 UTC, andistorm commented on docker/images/everest-clang-format/Dockerfile
> +ENV CLANG_FORMAT_RELEASE_TAG=llvmorg-15.0.6
1. This would bind the ci to this repository `everest/everest-ci` I made the complete workflow parametrized. This allows to test and run it also on forked repositories before merging. Else you would need to change this line any time you are working on this, just to change it back afterwards 

2. I would agree if we would build from source but in this case it describes exactly the version of the place we took it from. It is the tag used for the llvm release

3. Yeah we could change it to an `ARG`, but realistically we don't know the file naming regex for future releases of clang-format. So I would declare this Dockerfile valid for exactly this release version

2023-12-14 09:50 UTC, andistorm commented on docker/images/everest-clang-format/Dockerfile
> +ARG TARGETPLATFORM
I also found this doc. It says:
```
These arguments are defined in the global scope so are not automatically available inside build stages or for your RUN commands. To expose one of these arguments inside the build stage redefine it without value.
```

2023-12-14 09:51 UTC, andistorm commented on .github/workflows/build-and-deploy-docker-images.yaml
> +            image_name: ${{ github.repository_owner }}/everest-clang-format
Right now we already have an image called `everest-clang-format`. But I agree we could discuss renaming it, furthermore discuss naming strategy for our docker images

2023-12-15 14:00 UTC, Dominik-K commented on .github/workflows/build-and-deploy-docker-images.yaml
With "unfinished" I mean that they're based on potentially breaking and non-reviewed commits. 

(Note: "Tags" are in Docker-speech the part after the `:`, i.e. what's commonly called a version. But I think you know that already. Added here just for clarification.)

2023-12-15 14:12 UTC, Dominik-K commented on docker/images/everest-clang-format/Dockerfile
> +ARG TARGETPLATFORM
Aha, sorry, I have overseen this :+1:

Best you add a comment simply explaining this with a link to this reference. Then it's noted for the next reader who didn't know this :smile:

2023-12-15 14:49 UTC, Dominik-K commented on docker/images/everest-clang-format/Dockerfile
> +RUN apt update && apt upgrade -y
Good find. Didn't know that. Thanks :+1: 
Ok, then can you add this explanation as a comment, `please?` With reference, too.

However, I'm not sure if we really need to make sure that this Docker-image needs to be that secured. Where do you see an attack-vector?

2023-12-15 14:57 UTC, Dominik-K commented on docker/images/everest-clang-format/Dockerfile
> +ENTRYPOINT ["/usr/bin/run-clang-format.py"]
> This way it is possible to use the build stage as build target and run it for debugging purposes
Don't get it. When you need to debug it, you could add these lines anyway as you have access to the Dockerfile. But these lines aren't needed for debugging, anyway.

Actually, looking again, I don't see the need for an extra build-stage at all. Both stages use the same image.

2023-12-15 14:58 UTC, Dominik-K commented on docker/images/everest-clang-format/Dockerfile
> +FROM python:3.11.7-slim-bookworm as slim
Any reason why you're not using the Alpine-based image? It's even smaller than the slim Debian-variant. But it has `wget` by default :smile:

Hmm, is this also security-related? I'm curious about your knowledge :detective:

2023-12-15 14:58 UTC, Dominik-K commented on docker/images/everest-clang-format/Dockerfile
> +    wget
Oh, ok. As said, I just guessed.

2023-12-18 11:33 UTC, hikinggrass commented on .github/workflows/build-and-deploy-docker-images.yaml
> +            image_name: ${{ github.repository_owner }}/everest-clang-format
Yes let's keep it everest-* for now and discuss naming more generally

2023-12-18 11:56 UTC, andistorm commented on docker/images/everest-clang-format/Dockerfile
> +ENTRYPOINT ["/usr/bin/run-clang-format.py"]
I would stay with an extra build-stage since `wget` technically is a build dependency and not necessary for runtime

2023-12-18 11:57 UTC, andistorm commented on .github/workflows/build-and-deploy-docker-images.yaml
In my eyes the build of docker images for working branches is an advantage. This way it is possible to test those images in real ci workflows

2023-12-18 11:59 UTC, andistorm commented on docker/images/everest-clang-format/Dockerfile
> +FROM python:3.11.7-slim-bookworm as slim
This is just because we use debian based dynamically linked clang-format binary

2023-12-18 12:02 UTC, andistorm commented on docker/images/build-kit/debian.Dockerfile
> -
Didn't deep dive in that topic. But the docker documentation links this code here:
https://github.com/moby/moby/blob/03e2923e42446dbb830c654d0eec323a0b4ef02a/contrib/mkimage/debootstrap#L82-L105

2024-04-29 08:32 UTC, andistorm commented
Closed in favour of:
- https://github.com/EVerest/everest-ci/pull/16
- https://github.com/EVerest/everest-utils/pull/119

2024-04-29 08:32 UTC, closed without merging